image:
- Ubuntu2004
- macOs
- Visual Studio 2019

configuration: Release
platform: x64
clone_depth: 1

for:
-
  matrix:
    only:
      - image: Ubuntu2004
  environment:
    CMAKE_PREFIX_PATH: /home/appveyor/Qt/5.15/gcc_64
  install:
    - sudo apt -qq update
    - sudo apt install -y mesa-common-dev libglu1-mesa-dev
  after_build:
  - strip screenshotgun
  before_deploy:
  - mkdir $HOME/release
  - zip $HOME/release/screenshotgun_linux.zip screenshotgun
-
  matrix:
    only:
      - image: macOs
  environment:
    CMAKE_PREFIX_PATH: /Users/appveyor/Qt/5.15/clang_64
  after_build:
  - strip screenshotgun.app/Contents/MacOS/screenshotgun
  before_deploy:
  - mkdir $HOME/release
  - zip -r $HOME/release/screenshotgun_macos.zip screenshotgun.app
-
  matrix:
    only:
      - image: Visual Studio 2019
  environment:
    CMAKE_PREFIX_PATH: C:\Qt\5.15.2\msvc2019_64
  before_deploy:
  - mkdir $HOME/release
  - 7z a -tzip $HOME/release/screenshotgun_windows.zip screenshotgun.exe

build_script:
- cmake -DCMAKE_BUILD_TYPE=Release .
- cmake --build . --config Release

deploy:
- provider: GitHub
  auth_token:
    secure: 0GaldFB6iA6/Op54kN+749ZPJ09jc458c74JxmaUm5vVsu7v56J4JZRmwSwqrmff
  artifact: $HOME/release/*
  on:
    APPVEYOR_REPO_TAG: true
