language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      services:
        - docker
      deploy:
          - provider: releases
            token:
              secure: fJeBVylUmL+C/S3QOHMUtBct1Gqulqxzmnb1ccN6eD1Tq3COObu0Pb4zJeYjw2vIDFAXu73Mh+/TLqjGg6miFRaTQbcC2opiSkYzjwLBwQYSFTSqciR/W8Dq28zLScXpjDyMG9l5jGlO5R704aU/WP6y9xevgOBaFsFdTup/Diw/qhxrv9dpszZOalRb0N6v8FGtf9NTL0mE+jCpIpKV+YzqUWVziBHZfLsrA6luRPo4ZdDH6F2ygqqF2/1kP4dqpDLx6nfxf4wDf/tcTWAGoXjZkagGnjw1RTKhWXJGZ97UCYFC8R6aIpNnzyF/JepsEXXx8XaAfFtEWPcfYLskWCIEiFi6uS5hT6BIXEuMiIKpquO1yxFYnbg+aQ8yFwzAO0mN1p5NcxORi4WOTV13ZfJm+evT/7/zRNeHcsRY/erUTnG6/FhrptSgMOPppWv0nNE/kleraGhjK0OBDUd/hQ6mbYZk+pKO4Fb/NCzPHcNt4HhOkslpXKrF33zj92Mywfyqc1PHV7tnWE9bBMEZ7o9FPOwM0qCnpm0G2nnG4+VJwEIVYVTzDmhBBdAnyOoOv9w+XWEmPrd1FD0cQFR+3GGKUiet5U37ZDIDPeWF6q+6ed9QYBMPXiza4uLKYkR3xM5ZycVignGgy8VQOupv6J0qoP0cGz073t0RWYp64Yw=
            file: $HOME/release/*
            file_glob: true
            skip_cleanup: true
            edge: true
            on:
              tags: true
    - os: osx
      addons:
        homebrew:
          packages:
          - qt
          update: true
      deploy:
          - provider: releases
            token:
              secure: fJeBVylUmL+C/S3QOHMUtBct1Gqulqxzmnb1ccN6eD1Tq3COObu0Pb4zJeYjw2vIDFAXu73Mh+/TLqjGg6miFRaTQbcC2opiSkYzjwLBwQYSFTSqciR/W8Dq28zLScXpjDyMG9l5jGlO5R704aU/WP6y9xevgOBaFsFdTup/Diw/qhxrv9dpszZOalRb0N6v8FGtf9NTL0mE+jCpIpKV+YzqUWVziBHZfLsrA6luRPo4ZdDH6F2ygqqF2/1kP4dqpDLx6nfxf4wDf/tcTWAGoXjZkagGnjw1RTKhWXJGZ97UCYFC8R6aIpNnzyF/JepsEXXx8XaAfFtEWPcfYLskWCIEiFi6uS5hT6BIXEuMiIKpquO1yxFYnbg+aQ8yFwzAO0mN1p5NcxORi4WOTV13ZfJm+evT/7/zRNeHcsRY/erUTnG6/FhrptSgMOPppWv0nNE/kleraGhjK0OBDUd/hQ6mbYZk+pKO4Fb/NCzPHcNt4HhOkslpXKrF33zj92Mywfyqc1PHV7tnWE9bBMEZ7o9FPOwM0qCnpm0G2nnG4+VJwEIVYVTzDmhBBdAnyOoOv9w+XWEmPrd1FD0cQFR+3GGKUiet5U37ZDIDPeWF6q+6ed9QYBMPXiza4uLKYkR3xM5ZycVignGgy8VQOupv6J0qoP0cGz073t0RWYp64Yw=
            file: $HOME/release/*
            file_glob: true
            skip_cleanup: true
            edge: true
            on:
              tags: true
    - os: windows
      cache:
        directories:
        - $HOME/Qt
      deploy:
          - provider: releases
            token:
              secure: fJeBVylUmL+C/S3QOHMUtBct1Gqulqxzmnb1ccN6eD1Tq3COObu0Pb4zJeYjw2vIDFAXu73Mh+/TLqjGg6miFRaTQbcC2opiSkYzjwLBwQYSFTSqciR/W8Dq28zLScXpjDyMG9l5jGlO5R704aU/WP6y9xevgOBaFsFdTup/Diw/qhxrv9dpszZOalRb0N6v8FGtf9NTL0mE+jCpIpKV+YzqUWVziBHZfLsrA6luRPo4ZdDH6F2ygqqF2/1kP4dqpDLx6nfxf4wDf/tcTWAGoXjZkagGnjw1RTKhWXJGZ97UCYFC8R6aIpNnzyF/JepsEXXx8XaAfFtEWPcfYLskWCIEiFi6uS5hT6BIXEuMiIKpquO1yxFYnbg+aQ8yFwzAO0mN1p5NcxORi4WOTV13ZfJm+evT/7/zRNeHcsRY/erUTnG6/FhrptSgMOPppWv0nNE/kleraGhjK0OBDUd/hQ6mbYZk+pKO4Fb/NCzPHcNt4HhOkslpXKrF33zj92Mywfyqc1PHV7tnWE9bBMEZ7o9FPOwM0qCnpm0G2nnG4+VJwEIVYVTzDmhBBdAnyOoOv9w+XWEmPrd1FD0cQFR+3GGKUiet5U37ZDIDPeWF6q+6ed9QYBMPXiza4uLKYkR3xM5ZycVignGgy8VQOupv6J0qoP0cGz073t0RWYp64Yw=
            file: /c/Users/travis/release/screenshotgun_windows.zip
            file_glob: true
            skip_cleanup: true
            edge: true
            on:
              tags: true

before_install:
  - bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/before_install.sh
install:
  - bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/install.sh
script:
  - bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/script.sh
before_deploy:
  - bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/before_deploy.sh
deploy:
  - provider: script
    script: bash $TRAVIS_BUILD_DIR/scripts/ci/$TRAVIS_OS_NAME/deploy.sh $TRAVIS_TAG
    skip_cleanup: true
    on:
      condition: "$TRAVIS_OS_NAME == linux"
      tags: true
